language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx opencl-headers
after_success:
  - curl -X POST http://readthedocs.org/build/pycl
script: nosetests
